{% set name = "hip" %}
{% set version = "6.1.0" %}
{% set major_version = version.split('.')[0] %}
{% set minor_version = version.split('.')[1] %}
{% set major_minor_version = ".".join(version.split(".")[:2]) %}
{% set patch_version = version.split('.')[2] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ROCm/HIP/archive/refs/tags/rocm-{{ version }}.tar.gz
    sha256: 6fd57910a16d0b54df822807e67b6207146233a2de5a46c6a05b940a21e2c4d7
    folder: hip

  - url: https://github.com/ROCm/clr/archive/refs/tags/rocm-{{ version }}.tar.gz
    sha256: 49b23eef621f4e8e528bb4de8478a17436f42053a2f7fde21ff221aa683205c7
    folder: clr
    patches:
      - 0001-Mark-raw-strings.patch
      - 0002-Remove-download-of-libamd64.so.5.patch
      - 0004-Fix-hip-config.cmake-when-it-is-not-a-symlink.patch

  - url: https://github.com/ROCm/llvm-project/archive/refs/tags/rocm-{{ version }}.tar.gz
    sha256: 6bd9912441de6caf6b26d1323e1c899ecd14ff2431874a2f5883d3bc5212db34
    folder: hipcc
    patches:
      - 0001-Remove-QUIET-from-cmake-rocm-detection.patch
      - 0002-Make-rocm-cmake-required.patch
      - 0003-Fix-cmake-backward-compatibility.patch

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}
    - {{ cdt('libx11-devel') }}
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-libegl-devel') }}
    - cmake
    - make
    - cppheaderparser
    - wget
    - python *
  host:
    - clangdev 17.*
    - numactl
    - llvmdev  17.*
    - ocl-icd
    - rocm-comgr {{ major_minor_version }}.*
    - rocr-runtime {{ major_minor_version }}.*
    - rocm-cmake {{ major_minor_version }}.*
    - zlib

outputs:
  - name: hip-runtime-amd
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - numactl
        - rocm-comgr {{ major_minor_version }}.*
        - rocr-runtime {{ major_minor_version }}.*
      run:
        - libnuma  # to work around missing run_exports in numactl
        - rocm-comgr {{ major_minor_version }}.*
        - rocr-runtime {{ major_minor_version }}.*
    files:
      - lib/.hipInfo
      - lib/cmake/hip/hip-targets*.cmake
      - lib/cmake/hip-lang/*.cmake
      - lib/cmake/hiprtc/*.cmake
      - lib/libamdhip64.so*
      - lib/libhiprtc.so*
      - lib/libhiprtc-builtins.so*
      - share/doc/hip/LICENSE.txt
    test:
      commands:
        - test -f $PREFIX/lib/.hipInfo
        - test -f $PREFIX/lib/libamdhip64.so

  - name: hip-devel
    requirements:
      run:
        - {{ pin_subpackage("hip-runtime-amd") }}
    run_exports:
      - {{ pin_subpackage("hip-runtime-amd") }}
    files:
      - bin/hipcc_cmake_linker_helper
      - bin/hipdemangleatp
      - bin/roc-obj
      - bin/roc-obj-extract
      - bin/roc-obj-ls
      - include/hip/amd_detail/*.h
      - include/hip/*.h
      - lib/cmake/hip/FindHIP.cmake
      - lib/cmake/hip/FindHIP/*.cmake
      - lib/cmake/hip/hip-config*.cmake
      - share/hip/version
    test:
      commands:
        - test -f $PREFIX/share/hip/version
        - test -f $PREFIX/lib/cmake/hip/FindHIP.cmake
        - test -f $PREFIX/include/hip/hip_common.h

  - name: hipcc
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage("hip-devel", exact=True) }}
      run:
        - {{ pin_subpackage("hip-devel", exact=True) }}
        - clang
        - clangxx
        - llvm-tools
        - perl
        - python *
        - rocminfo {{ major_minor_version }}.*
    files:
      - bin/hipcc
      - bin/hipcc.bin
      - bin/hipcc.pl
      - bin/hipconfig*
      - bin/hipvars.pm
      - share/doc/hipcc/*
    test:
      commands:
        - $PREFIX/bin/hipcc --offload-arch=gfx803 --version
        - $PREFIX/bin/hipconfig

  - name: rocm-opencl
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - numactl
        - rocm-comgr {{ version }}
        - rocr-runtime {{ version }}
      run:
        - {{ pin_compatible("rocm-comgr") }}
        - {{ pin_compatible("rocr-runtime") }}
        - libnuma
    files:
      - lib/libamdocl64.so
      - share/doc/opencl/LICENSE.txt
    test:
      commands:
        - test -f $PREFIX/lib/libamdocl64.so

  - name: rocm-opencl-runtime
    requirements:
      run:
        - {{ pin_subpackage("rocm-opencl", exact=True) }}
        - ocl-icd                 # [linux]
        - khronos-ocl-icd-loader  # [not linux]
    files:
      - etc/OpenCL/vendors/amdocl64.icd
    test:
      commands:
        - test -f $PREFIX/etc/OpenCL/vendors/amdocl64.icd

about:
  home: https://github.com/ROCm/HIP
  license: NCSA
  license_family: MIT
  license_file:
    - clr/LICENCE
    - hip/LICENSE.txt
    - hipcc/amd/hipcc/LICENSE.txt
  summary: 'HIP: C++ Heterogeneous-Compute Interface for Portability '

extra:
  recipe-maintainers:
    - isuruf
    - zklaus
