{% set name = "hip" %}
{% set version = "6.4.0" %}
{% set major_version = version.split('.')[0] %}
{% set minor_version = version.split('.')[1] %}
{% set major_minor_version = ".".join(version.split(".")[:2]) %}
{% set patch_version = version.split('.')[2] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ROCm/HIP/archive/refs/tags/rocm-{{ version }}.tar.gz
    sha256: bec899ba67df9aa7056297e5ad104b8e36938b1bab22f1f418f69a8e0043d07f
    folder: hip

  - url: https://github.com/ROCm/clr/archive/refs/tags/rocm-{{ version }}.tar.gz
    sha256: 76fd0ad83da0dabf7c91ca4cff6c51f2be8ab259e08ad9743af47d1b3473c2ff
    folder: clr
    patches:
      - 0001-Mark-raw-strings.patch

  - url: https://github.com/ROCm/llvm-project/archive/refs/tags/rocm-{{ version }}.tar.gz
    sha256: dca1c145a23f05229d5d646241f9d1d3c5dbf1d745b338ae020eabe33beb965c
    folder: hipcc
    patches:
      - 0001-Make-cmake-rocm-detection-required.patch
      - 0002-Fix-cmake-backward-compatibility.patch
      - hipcc-path.diff

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}
    - {{ cdt('libx11-devel') }}
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-libegl-devel') }}
    - cmake
    - make
    - cppheaderparser
    - wget
    - python *
  host:
    - clangdev 19.*
    - numactl
    - llvmdev 19.*
    - ocl-icd
    - rocm-comgr {{ major_minor_version }}.*
    - rocr-runtime {{ major_minor_version }}.*
    - rocm-cmake {{ major_minor_version }}.*
    - zlib
    - rocminfo {{ major_minor_version }}.*

outputs:
  - name: hip-runtime-amd
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - numactl
        - rocm-comgr {{ major_minor_version }}.*
        - rocr-runtime {{ major_minor_version }}.*
      run:
        - libnuma  # to work around missing run_exports in numactl
        - rocm-comgr {{ major_minor_version }}.*
        - rocr-runtime {{ major_minor_version }}.*
    files:
      - lib/.hipInfo
      - lib/cmake/hip/hip-targets*.cmake
      - lib/cmake/hip-lang/*.cmake
      - lib/cmake/hiprtc/*.cmake
      - lib/libamdhip64.so*
      - lib/libhiprtc.so*
      - lib/libhiprtc-builtins.so*
      - share/doc/hip/LICENSE.txt
    test:
      commands:
        - test -f $PREFIX/lib/.hipInfo
        - test -f $PREFIX/lib/libamdhip64.so

  - name: hip-devel
    requirements:
      run:
        - {{ pin_subpackage("hip-runtime-amd") }}
    run_exports:
      - {{ pin_subpackage("hip-runtime-amd") }}
    files:
      - bin/hipcc_cmake_linker_helper
      - bin/hipdemangleatp
      - bin/roc-obj
      - bin/roc-obj-extract
      - bin/roc-obj-ls
      - include/hip/amd_detail/*.h
      - include/hip/*.h
      - lib/cmake/hip/FindHIP.cmake
      - lib/cmake/hip/FindHIP/*.cmake
      - lib/cmake/hip/hip-config*.cmake
      - share/hip/version
    test:
      commands:
        - test -f $PREFIX/share/hip/version
        - test -f $PREFIX/lib/cmake/hip/FindHIP.cmake
        - test -f $PREFIX/include/hip/hip_common.h

  - name: hipcc
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage("hip-devel", exact=True) }}
      run:
        - {{ pin_subpackage("hip-devel", exact=True) }}
        - clang
        - clangxx
        - llvm-tools
        - perl
        - python *
        - rocminfo {{ major_minor_version }}.*
    files:
      - bin/hipcc
      - bin/hipcc.bin
      - bin/hipcc.pl
      - bin/hipconfig*
      - bin/hipvars.pm
      - share/doc/hipcc/*
    test:
      commands:
        - export HIP_PLATFORM=amd
        - $PREFIX/bin/hipcc --offload-arch=gfx803 --version
        - $PREFIX/bin/hipconfig

  - name: rocm-opencl
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
      host:
        - numactl
        - rocm-comgr {{ version }}
        - rocr-runtime {{ version }}
      run:
        - {{ pin_compatible("rocm-comgr") }}
        - {{ pin_compatible("rocr-runtime") }}
        - libnuma
    files:
      - lib/libamdocl64.so*
      - share/doc/opencl/LICENSE.txt
    test:
      commands:
        - test -f $PREFIX/lib/libamdocl64.so

  - name: rocm-opencl-runtime
    requirements:
      run:
        - {{ pin_subpackage("rocm-opencl", exact=True) }}
        - ocl-icd                 # [linux]
        - khronos-ocl-icd-loader  # [not linux]
    files:
      - etc/OpenCL/vendors/amdocl64.icd
    test:
      commands:
        - test -f $PREFIX/etc/OpenCL/vendors/amdocl64.icd

about:
  home: https://github.com/ROCm/HIP
  license: NCSA
  license_family: MIT
  license_file:
    - clr/LICENCE
    - hip/LICENSE.txt
    - hipcc/amd/hipcc/LICENSE.txt
  summary: 'HIP: C++ Heterogeneous-Compute Interface for Portability '

extra:
  recipe-maintainers:
    - isuruf
    - zklaus
