{% set name = "hip" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ROCm/HIP/archive/refs/tags/rocm-{{ version }}.tar.gz
    sha256: b47178db94f2acc106e1a88ceb029844805266ebaba11ef63744e90d224b11be
    folder: hip

  - url: https://github.com/ROCm/clr/archive/refs/tags/rocm-{{ version }}.tar.gz
    sha256: cb8ac610c8d4041b74fb3129c084f1e7b817ce1a5a9943feca1fa7531dc7bdcc
    folder: clr
    patches:
      - 0001-Don-t-try-to-install-windows-files-on-linux.patch
      - 0001-Mark-raw-strings.patch
      - 0002-Remove-download-of-libamd64.so.5.patch

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}
    - {{ cdt('libx11-devel') }}
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-libegl-devel') }}
    - sysroot_linux-64 2.17  # [linux64]
    - cmake
    - make
    - cppheaderparser
    - wget
  host:
    - clangdev 17.*
    - hipcc                {{ version }}
    - libnuma
    - llvmdev  17.*
    - ocl-icd
    - rocm-cmake           {{ version }}
    - rocm-comgr           {{ version }}
    - rocr-runtime         {{ version }}
    - zlib
  run:
    - rocm-comgr           {{ version }}
    - rocr-runtime         {{ version }}

test:
  requires:
    - hipcc                {{ version }}
  commands:
    - $PREFIX/bin/hipcc --amdgpu-target=gfx803 --version
    - $PREFIX/bin/hipify-clang --version
    - $PREFIX/bin/hipconfig

about:
  home: https://github.com/ROCm/HIP
  license: NCSA
  license_family: MIT
  license_file:
    - clr-LICENSE
    - hip-LICENSE.txt
  summary: 'HIP: C++ Heterogeneous-Compute Interface for Portability '

extra:
  recipe-maintainers:
    - isuruf
    - zklaus
