{% set name = "hip" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/ROCm/HIP/archive/refs/tags/rocm-{{ version }}.tar.gz
    sha256: b47178db94f2acc106e1a88ceb029844805266ebaba11ef63744e90d224b11be
    folder: hip

  - url: https://github.com/ROCm/clr/archive/refs/tags/rocm-{{ version }}.tar.gz
    sha256: cb8ac610c8d4041b74fb3129c084f1e7b817ce1a5a9943feca1fa7531dc7bdcc
    folder: clr
    patches:
      - 0001-Don-t-try-to-install-windows-files-on-linux.patch
      - 0001-Mark-raw-strings.patch
      - 0002-Remove-download-of-libamd64.so.5.patch

  - url: https://github.com/ROCm/HIPCC/archive/refs/tags/rocm-{{ version }}.tar.gz
    sha256: d6209b14fccdd00d7231dec4b4f962aa23914b9dde389ba961370e8ba918bde5
    folder: hipcc
    patches:
      - 0001-Remove-QUIET-from-cmake-rocm-detection.patch
      - 0002-Make-rocm-cmake-required.patch
      - 0003-Fix-cmake-backward-compatibility.patch

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}
    - {{ cdt('libx11-devel') }}
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-libegl-devel') }}
    - sysroot_linux-64 2.17  # [linux64]
    - cmake
    - make
    - cppheaderparser
    - wget
  host:
    - clangdev 17.*
    - numactl
    - llvmdev  17.*
    - ocl-icd
    - python
    - rocm-cmake           {{ version }}
    - rocm-comgr           {{ version }}
    - rocr-runtime         {{ version }}
    - zlib
  run:
    - clang
    - clangxx
    - libnuma
    - llvm-tools
    - perl
    - python
    - rocm-comgr           {{ version }}
    - rocminfo             {{ version }}
    - rocr-runtime         {{ version }}

outputs:
  - name: hip-runtime-amd
    files:
      - lib/.hipInfo
      - lib/cmake/hip/hip-targets*.cmake
      - lib/cmake/hip-lang/*.cmake
      - lib/cmake/hiprtc/*.cmake
      - lib/libamdhip64.so*
      - lib/libhiprtc.so*
      - lib/libhiprtc-builtins.so*
      - share/doc/hip/LICENSE.txt

  - name: hip-devel
    files:
      - bin/hipcc_cmake_linker_helper
      - bin/hipdemangleatp
      - bin/roc-obj
      - bin/roc-obj-extract
      - bin/roc-obj-ls
      - include/hip/amd-detail/*.h
      - include/hip/*.h
      - lib/cmake/hip/FindHIP.cmake
      - lib/cmake/hip/FindHIP/*.cmake
      - lib/cmake/hip/hip-config*.cmake
      - share/hip/version

  - name: hipcc
    files:
      - bin/hipcc
      - bin/hipcc.bin
      - bin/hipcc.pl
      - bin/hipconfig*
      - bin/hipvars.pm
      - share/doc/hipcc/*

  - name: rocm-opencl
    files:
      - lib/libamdocl64.so
      - share/doc/opencl/LICENSE.txt

test:
  commands:
    - $PREFIX/bin/hipcc --offload-arch=gfx803 --version
    - $PREFIX/bin/hipconfig

about:
  home: https://github.com/ROCm/HIP
  license: NCSA
  license_family: MIT
  license_file:
    - clr/LICENCE
    - hip/LICENSE.txt
    - hipcc/LICENSE.txt
  summary: 'HIP: C++ Heterogeneous-Compute Interface for Portability '

extra:
  recipe-maintainers:
    - isuruf
    - zklaus
