{% set name = "hip" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ROCm/HIP/archive/refs/tags/rocm-{{ version }}.tar.gz
  sha256: b47178db94f2acc106e1a88ceb029844805266ebaba11ef63744e90d224b11be

build:
  number: 0
  skip: True  # [not linux]
  merge_build_host: True

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - perl *
  host:
    - rocr-runtime         {{ ".".join(version.split(".")[:2]) }}
    - rocm-device-libs     {{ ".".join(version.split(".")[:2]) }}
    - roct-thunk-interface {{ ".".join(version.split(".")[:2]) }}
    - rocm-comgr           {{ ".".join(version.split(".")[:2]) }}
    - clangdev
    - llvmdev
    - llvm
    - perl *
  run:
    - {{ pin_compatible("rocr-runtime", max_pin="x.x") }}
    - {{ pin_compatible("rocm-comgr", max_pin="x.x") }}
    - {{ pin_compatible("roct-thunk-interface", max_pin="x.x") }}
    - rocminfo
    - perl *

test:
  commands:
    - $PREFIX/bin/hipcc --amdgpu-target=gfx803 --version
    - $PREFIX/bin/hipify-clang --version
    - $PREFIX/bin/hipconfig

about:
  home: https://github.com/ROCm-Developer-Tools/HIP
  license: NCSA
  license_family: MIT
  license_file: LICENSE
  summary: 'HIP : Convert CUDA to Portable C++ Code'

extra:
  recipe-maintainers:
    - isuruf
